# Generated by Django 4.2.11 on 2024-12-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
