# Generated by Django 4.2.11 on 2024-12-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseit_app', '0003_sections_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='course',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
    ]
