# Generated by Django 4.2.11 on 2024-12-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseit_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courseit_app.sections'),
        ),
    ]
