# Generated by Django 4.2.11 on 2024-12-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseit_app', '0006_alter_chapter_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courseit_app.sections'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=models.TextField(),
        ),
    ]
