# Generated by Django 5.1.4 on 2024-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseit_app', '0007_alter_chapter_options_remove_chapter_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
